version: "3.8"

services:
  web:
    build: .
    container_name: uploader_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - redis

  db:
    image: postgres
    container_name: uploader_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  pgdata:





